name: Build ALL
run-name: Build ALL
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-22.04
    # needs: [Build_Android, Build_Windows]
    steps:
      - name: Get latest tag via API
        id: get_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/venera-app/venera/tags \
            | jq -r '.[0].name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "Latest tag: $latest_tag"
      # 创建 Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          prerelease: ${{ env.PRERELEASE == 'true' }}
          generate_release_notes: true
          files: |
            outputs/*.apk
            outputs/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
