name: Android

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
      - name: Build APK
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_FILE_BASE64: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: |
          base64 -d <<< $ANDROID_STORE_FILE_BASE64 > android/app/release-key.jks 
          echo -e "storePassword=$ANDROID_STORE_PASSWORD\nkeyPassword=$ANDROID_KEY_PASSWORD\nkeyAlias=$ANDROID_KEY_ALIAS\nstoreFile=release-key.jks" >> android/key.properties 
          flutter pub get
          flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk
      
  release:
    runs-on: ubuntu-latest
    needs: android_build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: flutter-apk
          path: outputs
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: outputs/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
